### ISSUE TITLE
.net version and parameter problems

### ISSUE THREAD

**Issue by hl0rey** [b4rtik/metasploit-execute-assembly#6]
Hi b4rtik,
I am having some problems with your MSF module and I look forward to hearing from you.
Based on my understanding, I have solved the problem and made some Suggestions to you. It is up to you to adopt them.
Fristly,I feel there may be a slip of the pen here.Beacause from the point of view of the code logic, the value 3 should not appear.When I changed the 3 to 2, I ran the application successfully in the environment of win2008+.net2.0.
![image](https://user-images.githubusercontent.com/34831863/91121337-25316d80-e6ca-11ea-9aca-976c2114b7ea.png)
seconedly,there was an error in the number of arguments while executing the.net program.
![image](https://user-images.githubusercontent.com/34831863/91121427-5742cf80-e6ca-11ea-918b-708859b3e9bb.png)
![image](https://user-images.githubusercontent.com/34831863/91121453-66298200-e6ca-11ea-9ef0-72c40dfa7acc.png)
When I looked at the code, I found that if I did not pass in parameters, the number of parameters would be set to 0. I felt that this might not be reasonable. I tried to arbitrarily set one parameter, and the program ran successfully.
![image](https://user-images.githubusercontent.com/34831863/91123901-91af6b00-e6d0-11ea-930c-458f52aa3705.png)
![image](https://user-images.githubusercontent.com/34831863/91124449-d12a8700-e6d1-11ea-8e83-92dbe669f772.png)
The program runs with at least one parameter, and that is itself, and I think that's probably the problem.
By the way, I used the official MSF module for testing, but I submitted the issue to MSF for fear that I could not contact you, so I submitted it here.
Thank you for reading my issue. I hope you can let me know if you have any ideas.

**Comment by hl0rey** [comment]
![image](https://user-images.githubusercontent.com/34831863/91158231-ecf55380-e6f8-11ea-9258-98839a32e2c1.png)

**Comment by b4rtik** [comment]
Thanks for reporting the bug. I'll check out soon

**Comment by b4rtik** [comment]
Well as for the version of .Net Framework installed, actually correct the value is 3.
This is because the version of the Framework is detected via the registry and a function already present in metaslpoit-framework has been used (check https://github.com/rapid7/metasploit-framework/blob/5368536d1a167a226898d3787d0fbf5bbff9a1ec/lib/msf/core/post/windows/dotnet.rb)

Which returns the value of the "Version" subkey

Remember .Net Framework version (3.5 4.0 4.6 etc) and CLR version (v2.0.50727, v4.0.30319) are not the same thing.

In any case, no one forbids extending support to version 2 as well.

The second point, on the other hand, is a little more obscure and should probably be documented a bit in the help.

We need to manage the following scenarios:

The assembly has a signature like this

`static void Main (string [] args)`

In this case a newly loaded module, even without specifying parameters, runs correctly.

But if you run for example

`unset arguments`

You are telling the module that you want to run an assembly with the following signature

`static void Main ()`

Which requires 

`SafeArrayCreateVector(VT_VARIANT, 0,0)`

To restore you can use 

`set arguments ""`

However, there may be an error and as soon as I have the opportunity I will do some tests, but the logic described above must be taken into account

**Comment by hl0rey** [comment]
Thank you for your reply.Until now, I had been confusing the CLR version with the.NET version.I will carry out further tests and let you know if I have any new findings.
